- sonarakendus/sonarakendus/javascript/tekst.js
- ui/public/sonarakendus/javascript/tekst.js
Siin ei ole midagi rohkem vaja testida. Kui kood sobib, võib kohe devi pushida.
> Teksti eelvaates uue rea (\n) parandus

- api/src/main/java/ee/tlu/evkk/api/controller/TextController.java
- api/src/main/java/ee/tlu/evkk/api/dao/TextDao.java
- api/src/main/resources/ee/tlu/evkk/api/dao/TextDao.xml
- sonarakendus/sonarakendus/javascript/paring.js
- sonarakendus/sonarakendus/javascript/tekst.js
- sonarakendus/sonarakendus/javascript/vahekorpus2.js
- sonarakendus/sonarakendus/paring.html
- sonarakendus/sonarakendus/tekst.html
- ui/public/sonarakendus/javascript/paring.js
- ui/public/sonarakendus/javascript/tekst.js
- ui/public/sonarakendus/javascript/vahekorpus2.js
- ui/public/sonarakendus/paring.html
- ui/public/sonarakendus/tekst.html
- ui/src/Nav.js
Siin ei ole midagi rohkem vaja testida. Kui kood sobib, võib kohe devi pushida.
> Päring arvestab vana ja uue metainfo märgendusega

- sonarakendus/sonarakendus/javascript/paring.js
- sonarakendus/sonarakendus/paring.html
- sonarakendus/sonarakendus/styles/paring.css
- ui/public/sonarakendus/javascript/paring.js
- ui/public/sonarakendus/paring.html
- ui/public/sonarakendus/styles/paring.css
Siin ei ole midagi rohkem vaja testida. Kui kood sobib, võib kohe devi pushida.
> Päringusse lisatud loading screen animatsioonid

- ui/src/views/tools/wordanalyser/GrammaticalAnalysis.js
- ui/src/views/tools/wordanalyser/LemmaView.js
- ui/src/views/tools/wordanalyser/Syllables.js
Added functionality to make word analyzer tables sort by frequency on default.
> Default tabler sorting

- ui/src/views/tools/wordanalyser/Syllables.js
Percentage column added to syllable table.
> Added the percentage column to the syllable table.

- ui/src/views/tools/wordanalyser/GrammaticalAnalysis.js
- ui/src/views/tools/wordanalyser/LemmaView.js
- ui/src/views/tools/wordanalyser/Syllables.js
- ui/src/views/tools/wordanalyser/styles/GrammaticalAnalysis.css
- ui/src/views/tools/wordanalyser/styles/LemmaView.css
- ui/src/views/tools/wordanalyser/styles/Syllables.css
Changed around column sorting and did minor improvements to table headers.
> New sorting

- ui/src/views/tools/wordanalyser/GrammaticalAnalysis.js
- ui/src/views/tools/wordanalyser/LemmaView.js
- ui/src/views/tools/wordanalyser/Syllables.js
- ui/src/views/tools/wordanalyser/WordAnalyser.js
- ui/src/views/tools/wordanalyser/styles/GrammaticalAnalysis.css
Changed tables so they won't reset when clicking on table rows.
> Fixed table reset issue

- ui/src/views/tools/wordanalyser/GrammaticalAnalysis.js
> Fixed issue where filter closed when clicking select item.

- ui/src/elle/pages/Contacts.js
- ui/src/elle/pages/Links.js
> Linkide stiilimuutused

- clusterfinder/src/main/resources/messages_et.properties
- clusterfinder/src/main/resources/templates/clusterSearch.ftl
Z-inexi kuutus. Otsingukriteeriumite muutused.
> Väikesed muutused klasterdajas

- api/src/main/java/ee/tlu/evkk/api/controller/TextController.java
- api/src/main/java/ee/tlu/evkk/api/controller/dto/AddingRequestEntity.java
- dal/src/main/java/ee/tlu/evkk/dal/dao/TextDao.java
- dal/src/main/resources/ee/tlu/evkk/dal/dao/TextDao.xml
- db/src/main/resources/migration/versioned/V0005__Migration.sql
- ui/src/AppRoutes.js
- ui/src/elle/components/Adding.component.js
Sisestusvorm, lisab tekstid ja metaandmed uude tabelisse
> Tekstide üleslaadimine

- api/src/main/java/ee/tlu/evkk/api/controller/TextController.java
- ui/src/elle/components/Adding.component.js
1) "Ennista andmed" - vasakul pool peavad väljad tühjenema, paremal pool peavad säilima
2) Tühikuviga loa tekstis esimese lõigu lõpus: "ning keeleõppija"
3) Abimaterjalide valik - rippmenüüsse linnukesed, et kasutaja saaks aru, et tal on mitu valikut (vt Harli koodi)
4) Emakeel - väärtus tuleb enne andmebaasi sisestamist väiketähestada
Mitteakadeemilised tekstid:
Abimaterjalide menüü ei avane - kasuta sama menüüd mis akadeemilistel tekstidel
> Akadeemilised tekstid:

- ui/src/elle/components/Adding.component.js
- ui/src/elle/components/styles/Adding.css
> Sisestuskasti kujundus

- clusterfinder/src/main/resources/templates/clusterSearch.ftl
- ui/src/elle/components/IntegrationFrame.js
Integration frame muutmine classilt funktsioonile. Iframe'i parem integreerimine. Scrollbari eemaldamine.
> Iframe integreerimine

- ui/src/elle/pages/query/Query.js
- ui/src/elle/pages/query/QueryResults.js
Lisasin, et päringu valikuid saab muuta peale esmast päringud.
> ELLE-249 | Query options not resetting

- ui/src/elle/components/IntegrationFrame.js
- ui/src/elle/components/styles/HeroElement.css
- ui/src/elle/components/styles/TablePagination.css
- ui/src/elle/components/table/TablePagination.js
- ui/src/elle/pages/query/Query.js
- ui/src/elle/pages/query/QueryResults.js
- ui/src/elle/pages/styles/QueryResults.css
- ui/src/elle/tools/wordanalyser/WordAnalyser.js
- ui/src/elle/translations/en/translations.js
- ui/src/elle/translations/et/translations.js
Tegin tagasinupu ning päringud jäävad meelde. Lisaks parandasin Esilehel Hero nupu.
> ELLE-252 | query, wordanalyser connection & front page button fixes

- ui/src/AppRoutes.js
- ui/src/elle/components/home/ServicesElement.js
- ui/src/elle/components/styles/ServicesElement.css
- ui/src/elle/const/Constants.js
- ui/src/elle/pages/Tools.js
- ui/src/elle/tools/collocates/Collocates.js
- ui/src/elle/tools/wordcontext/WordContext.js
- ui/src/elle/tools/wordlist/Wordlist.js
- ui/src/elle/translations/en/translations.js
- ui/src/elle/translations/et/translations.js
Sidusin tööriistade tabid lehe URL-iga. Muudatused avalehe kujunduses.
> ELLE-220 | Kodulehe ja tööriistade lehe parandus

- ui/src/elle/pages/Tools.js
Tool windows stay active while texts are selected.
> ELLE-252 | Tool tabs not staying active

- stanza-server/valemid_mitmekesisus.py
- ui/src/elle/tools/correction/Correction.js
Fixed min 50 words error in "stanza-server". Changed table descriptions. Added space to row changes in input text.
> ELLE-253 | Corrector fixes

- ui/src/elle/components/SingleLink.js
- ui/src/elle/const/Constants.js
- ui/src/elle/pages/Tools.js
- ui/src/elle/pages/query/Query.js
- ui/src/elle/pages/query/QueryResults.js
- ui/src/elle/tools/correction/Correction.js
- ui/src/elle/tools/correction/WordClick.js
- ui/src/elle/tools/wordanalyser/textinput/InputText.js
Removed most warnings and errors that occured when rendering the UI
> ELLE-244 | UI warnings fix

- ui/src/elle/components/about/ContactCard.js
- ui/src/elle/pages/query/Query.js
- ui/src/elle/pages/styles/Query.css
- ui/src/elle/pages/styles/Tools.css
Removed getelementbyID and replaced with usestate and useref in query buttons and divs.
> ELLE-238 | Query window from JS to React

- ui/src/elle/pages/Tools.js
- ui/src/elle/pages/query/Query.js
- ui/src/elle/pages/styles/Tools.css
Hide Tools tab when query component is displayed.
> ELLE-264 | Hide tools

- ui/src/elle/components/IntegrationFrame.js
- ui/src/elle/service/TextService.js
- ui/src/elle/tools/wordanalyser/WordAnalyser.js
- ui/src/elle/util/TextUtils.js
Moved query post request into separate component TextService and moved replaceAll regular expression into separate component TextService
> ELLE-248 | Query POST request component

- ui/src/elle/components/table/TableDownloadButton.js
- ui/src/elle/pages/query/Query.js
- ui/src/elle/tools/wordanalyser/GrammaticalAnalysis.js
- ui/src/elle/tools/wordanalyser/LemmaView.js
- ui/src/elle/tools/wordanalyser/Syllables.js
- ui/src/elle/tools/wordanalyser/WordAnalyserParent.js
- ui/src/elle/tools/wordanalyser/styles/GrammaticalAnalysis.css
Changed wordanalyser table button styles. Made wordanalyser tables more responsive.
Was unable to replicate sorting error in dev environment.
> ELLE-265 | Table not responsive, sorting error.

- ui/src/elle/components/IntegrationFrame.js
- ui/src/elle/components/Navbar.js
- ui/src/elle/const/Constants.js
- ui/src/elle/pages/Links.js
- ui/src/elle/pages/styles/Links.css
- ui/src/elle/resources/images/link-images/index.js
- ui/src/elle/tools/correction/Correction.css
- ui/src/elle/tools/correction/WordClick.js
- ui/src/elle/translations/et/translations.js
Changed on page link anchors, added ELLE borders to link container and moved inline styles to css file.
> ELLE-272 | Links page changes

- ui/src/elle/pages/query/Query.js
Changed previously open query tab to close when new tab is opened.
> ELLE-274 | Query tabs fix

- ui/src/elle/const/Constants.js
- ui/src/elle/tools/correction/Correction.js
Changed scale design and made scales dynamic
> ELLE-262 | Corrector scale fixes

- clusterfinder/src/main/resources/templates/clusterSearch.ftl
- clusterfinder/src/main/resources/templates/common/inputs.ftl
Changed clusterfinder styles to match ELLE design. Removed input box.
> ELLE-232 | Clusterfinder style changes

- LICENSE.md
- README.md
Renewed the ReadME info, indlucing the corpus licensing terms.
> Readme changes

- db/src/main/resources/migration/repeatable/R__0012-core.text_exam.sql
Kaisiga kontrollisime üle - nüüd on uued tekstid ka haridustaseme järgi kättesaadavad
> ELLE-144 | eksamitekstid

- stanza-server/server.py
- ui/src/elle/const/Constants.js
- ui/src/elle/tools/wordanalyser/WordAnalyser.js
- ui/src/elle/tools/wordanalyser/WordAnalyserParent.js
- ui/src/elle/tools/wordanalyser/styles/WordAnalyser.css
- ui/src/elle/tools/wordanalyser/textinput/InputText.js
- ui/src/elle/translations/en/translations.js
- ui/src/elle/translations/et/translations.js
Fixed error in Word Analyzer where numbers and foreign characters in texts induced a crash.
> ELLE-298 | Word Analyzer crash

- stanza-server/server.py
- ui/src/elle/tools/correction/Correction.js
- ui/src/elle/tools/correction/const/TabValuesConstant.js
- ui/src/elle/tools/correction/tabviews/complexity/ComplexityTab.js
Fixed text changing bug on tab change. Fixed index values.
> ELLE-205 | Tab change text error

- ui/src/elle/tools/correction/Correction.js
- ui/src/elle/tools/correction/components/CorrectionButton.js
- ui/src/elle/tools/correction/components/CorrectionInput.js
- ui/src/elle/tools/correction/components/CorrectionToggleButtonGroup.js
- ui/src/elle/tools/correction/tabviews/complexity/ComplexityTab.js
- ui/src/elle/tools/correction/tabviews/vocabulary/VocabularyTab.js
- ui/src/elle/tools/correction/util/Utils.js
Optimised query caller function
> ELLE-315 | Query caller rework

- docker/images/evkk-grammar-worker-server.Dockerfile
- grammar-worker-server/server.py
- stanza-server/grammar_fetches.py
Added NELB GEC model as backup for GEC API
> ELLE-310 | Add NELB model

- common/src/main/java/ee/tlu/evkk/common/util/TextUtils.java
- stanza-server/linguistic_functions.py
- stanza-server/server.py
See parandab ära bugi, et numbreid märgitakse ja ühtlasi ka bugi, et rakendus plahvatab teatud tekstidega, kui "sisusõnad" vahekaardile minna.
> ELLE-317 | Normalize abstract list and lemma list

- ui/src/elle/tools/correction/const/Constants.js
- ui/src/elle/tools/correction/util/VocabularyMarkingHandlers.js
> ELLE-317 | Uncommon word bugfix

- ui/src/elle/const/StyleConstants.js
- ui/src/elle/tools/correction/Correction.js
- ui/src/elle/tools/correction/components/CorrectionButton.js
- ui/src/elle/tools/correction/components/CorrectionDocxDownloadButton.js
- ui/src/elle/tools/correction/components/CorrectionInput.js
- ui/src/elle/tools/correction/components/DownloadButton.js
- ui/src/elle/tools/correction/const/Constants.js
- ui/src/elle/tools/correction/const/TabValuesConstant.js
- ui/src/elle/tools/correction/tabviews/complexity/ComplexityTab.js
- ui/src/elle/tools/correction/tabviews/correction/CorrectionTab.js
- ui/src/elle/tools/correction/tabviews/textlevel/TextLevelTab.js
- ui/src/elle/tools/correction/tabviews/textlevel/components/TextLevelAccordionInner.js
- ui/src/elle/tools/correction/tabviews/vocabulary/VocabularyTab.js
- ui/src/elle/tools/correction/util/CorrectorErrorResolveFunctions.js
- ui/src/elle/tools/correction/util/Utils.js
- ui/src/elle/translations/en/translations.js
- ui/src/elle/translations/et/translations.js
Added option to download marked text as DOCX
> ELLE-297 | Corrector download button

- core/src/main/java/ee/tlu/evkk/core/service/dto/TextWithComplexity.java
- stanza-server/corrector_counters.py
- stanza-server/server.py
- stanza-server/vocabulary_marking_handlers.py
- ui/src/elle/tools/correction/const/Constants.js
- ui/src/elle/tools/correction/styles/VocabularyTab.css
- ui/src/elle/tools/correction/tabviews/vocabulary/VocabularyTab.js
- ui/src/elle/tools/correction/util/ComplexityCalculations.js
- ui/src/elle/tools/correction/util/ComplexityMarkingHandlers.js
- ui/src/elle/tools/correction/util/VocabularyCalculations.js
- ui/src/elle/tools/correction/util/VocabularyMarkingHandlers.js
Fix fir word repetition marking bugs.
> ELLE-321 | Vocabulary bugfixes for Writing Evaluator

- api/src/main/java/ee/tlu/evkk/api/controller/RootController.java
@jaagup sinu merge nupuvajutust siia vaja, tavaline merge mitte squash ega rebase
> Live deploy v25.1.1

- ui/src/elle/const/PublicationsAndGrantsConstants.js
Added new publications and grants related to the ELLE environment.
> ELLE-325 | Update publications and grants constants

- stanza-server/corrector_functions.py
- stanza-server/server.py
Fixed spelling word duplication and made frequent error list not case sensitive.
> ELLE-271 | Error list fixes

- stanza-server/text_level_model/linguistic_analysis.py
- stanza-server/text_level_model/linguistic_functions.py
- stanza-server/text_level_model/train.py
Fixes to the new text level model
> ELLE-307 | Fixes to new textlevel model
